auto: false
server: false
markdown: rdiscount
pygments: true
lsi: false
permalink: /:year/:month/:title
paginate: 10
category: topics
category_title_prefix: 
exclude: ["lib", "blog.rb", "Capfile", "config", "log", "Rakefile", "tmp", "docs"]
destination: _site

