# http://vitobotta.com/how-to-migrate-from-wordpress-to-jekyll/
# pygmentize -S colorful -f html > css/syntax.css

auto: false
server: false
markdown: rdiscount
pygments: true
lsi: false
permalink: /:year/:month/:title
paginate: 10
category: topics
category_title_prefix: 
exclude: ["lib", "blog.rb", "Capfile", "config", "log", "Rakefile", "tmp"]
destination: _site

